#!/usr/bin/python

# Function definition is here

   
def solution(s):
    #print (s)
    # Your code here
    alph2braille ={
        ' ':'000000',
        'a':'100000',
        'b':'110000',
        'c':'100100',
        'd':'100110',
        'e':'100010',
        'f':'110100',
        'g':'110110',
        'h':'110010',
        'i':'010100',
        'j':'010110',
        'k':'101000',
        'l':'111000',
        'm':'101100',
        'n':'101110',
        'o':'101010',
        'p':'111100',
        'q':'111110',
        'r':'111010',
        's':'011100',
        't':'011110',
        'u':'101001',
        'v':'111001',
        'w':'010111',
        'x':'101101',
        'y':'101111',
        'z':'101011'
    }
    
    braillecode = ""
    
    for i in s:
        if i.isupper() == True:
            print i
            braillecode = braillecode + '000001'
            
        print i,alph2braille[i.lower()]
        braillecode = braillecode + alph2braille[i.lower()]
        print braillecode
    
    asciicodes = [' ', 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    braillecodes = [
    '000000',
    '100000',
    '110000',
    '100100',
    '100110',
    '100010',
    '110100',
    '110110',
    '110010',
    '010100',
    '010110',
    '101000',
    '111000',
    '101100',
    '101110',
    '101010',
    '111100',
    '111110',
    '111010',
    '011100',
    '011110',
    '101001',
    '111001',
    '010111',
    '101101',
    '101111',
    '101011']
    
    plaintext = "a"
    
    print braillecodes[asciicodes.index(plaintext.lower())]
    
    string = "000001110000111010100000010100111000111000100010"
    return string

# Now you can call changeme function
print solution("Braille")
