#!/bin/python

import math
import os
import random
import re
import sys

# Complete the luckBalance function below.
def luckBalance(k, contests):
    n =  len(contests)

    important = []
    total_luck = []
    minus_luck = []

    for i in range(n):
        if contests[i][1] == 1:
            important.append(contests[i][0])
            important.sort()
            if len(important) > k:
                minus_luck.append(important[0])
                important.remove(important[0])
                
        else:
            total_luck.append( contests[i][0])
            
    #print important, total_luck, minus_luck


                
    return sum(important) + sum(total_luck) - sum(minus_luck)
    #return total_luck - minus_luck



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = raw_input().split()

    n = int(nk[0])

    k = int(nk[1])

    contests = []

    for _ in xrange(n):
        contests.append(map(int, raw_input().rstrip().split()))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
