#!/bin/python

import math
import os
import random
import re
import sys

# Complete the makeAnagram function below.
def makeAnagram(a, b):
    a = list(a)
    b = list(b) 

    a.sort()
    b.sort()

    la = len(a)
    lb = len(b)

    k=l=0
    
    for i in range(0,la):
        for j in range(l,lb):
            print a[i], b[j],k
            if a[i] == b[j]:
                k+=1
                l=j+1
                break

    return (la+lb)-2*k

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = raw_input()

    b = raw_input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
