#!/bin/python

from __future__ import print_function

import os
import sys
import time

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    #
    # Write your code here.
    #
   
    #print (s[-2:])
    if (s[-2:]) == 'PM':
        return (str(int(s[:2])+12)+s[2:8])
    else:
        return (s[:8])

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = raw_input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
